name: Lint & test

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.20

    - name: Install Make
      run: sudo apt-get install make

    - name: Run make lint
      run: make lint

    - name: Run make testacc
      run: make testacc
