name: Lint & test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: "stable"

    - name: Install Make
      run: sudo apt-get install make

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: "v2.12"

    - name: Run make testacc
      run: make testacc
